import 'package:flutter/material.dart';
import 'package:flutterapp/workoutapp/generatedonboardingscreenwidget/generated/GeneratedTaglineWidget3.dart';
import 'package:flutterapp/workoutapp/generatedonboardingscreenwidget/generated/GeneratedIllustrationWidget.dart';

/* Frame Onboarding Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboardingScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 29.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 269.0,
                child: GeneratedTaglineWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 492.0,
                child: GeneratedIllustrationWidget(),
              )
            ]),
      ),
    ));
  }
}
