description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^1.0.5"
  path_drawing: "^1.0.0"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.12.0 <3.0.5"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Inter-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Inter-900.ttf"
          style: "normal"
          weight: 900
    - 
      family: "Nunito"
      fonts: 
        - 
          asset: "fonts/Nunito-800.ttf"
          style: "normal"
          weight: 800
        - 
          asset: "fonts/Nunito-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Merriweather"
      fonts: 
        - 
          asset: "fonts/Merriweather-900.ttf"
          style: "normal"
          weight: 900
    - 
      family: "Poppins"
      fonts: 
        - 
          asset: "fonts/Poppins-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Kaushan Script"
      fonts: 
        - 
          asset: "fonts/KaushanScript-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
