import 'package:flutter/material.dart';
import 'package:flutterapp/workoutapp/generatedbehanceportfolioitemwidget1/generated/GeneratedFrame4Widget1.dart';
import 'package:flutterapp/workoutapp/generatedbehanceportfolioitemwidget1/generated/GeneratedCoverWidget1.dart';

/* Frame Behance Portfolio Item
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBehancePortfolioItemWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2315.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1400.0,
                      height: 2315.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1400.0,
                              height: 720.0,
                              child: GeneratedCoverWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 720.0,
                              right: null,
                              bottom: null,
                              width: 1400.0,
                              height: 1578.0,
                              child: GeneratedFrame4Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
