import 'package:flutter/material.dart';
import 'package:flutterapp/workoutapp/generatedcomponentswidget/generated/GeneratedNavigationbarWidget7.dart';
import 'package:flutterapp/workoutapp/generatedcomponentswidget/generated/GeneratedExerciseTitleWidget20.dart';
import 'package:flutterapp/workoutapp/generatedcomponentswidget/generated/GeneratedPilldateWidget28.dart';
import 'package:flutterapp/workoutapp/generatedcomponentswidget/generated/GeneratedCategorycardWidget4.dart';
import 'package:flutterapp/workoutapp/generatedcomponentswidget/generated/GeneratedIconswimmingWidget4.dart';
import 'package:flutterapp/workoutapp/generatedcomponentswidget/generated/GeneratedPillExerciseDetailsWidget12.dart';
import 'package:flutterapp/workoutapp/generatedcomponentswidget/generated/GeneratedStatusDurationWidget5.dart';
import 'package:flutterapp/workoutapp/generatedcomponentswidget/generated/GeneratedStatusDurationWidget4.dart';
import 'package:flutterapp/workoutapp/generatedcomponentswidget/generated/GeneratedIconrunningWidget6.dart';
import 'package:flutterapp/workoutapp/generatedcomponentswidget/generated/GeneratedIconbicycleWidget4.dart';

/* Frame Components
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComponentsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 785.0,
      height: 571.0,
      child: Stack(
          clipBehavior: Clip.none,
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 248, 248, 248),
              ),
            ),
            Positioned(
              left: 252.0,
              top: 373.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 15.0,
              child: GeneratedIconswimmingWidget4(),
            ),
            Positioned(
              left: 208.0,
              top: 371.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 15.0,
              child: GeneratedIconrunningWidget6(),
            ),
            Positioned(
              left: 228.0,
              top: 370.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 15.0,
              child: GeneratedIconbicycleWidget4(),
            ),
            Positioned(
              left: 347.0,
              top: 275.0,
              right: null,
              bottom: null,
              width: 373.0,
              height: 122.0,
              child: GeneratedPillExerciseDetailsWidget12(),
            ),
            Positioned(
              left: 196.0,
              top: 265.0,
              right: null,
              bottom: null,
              width: 66.0,
              height: 71.0,
              child: GeneratedPilldateWidget28(),
            ),
            Positioned(
              left: 347.0,
              top: 218.0,
              right: null,
              bottom: null,
              width: 126.0,
              height: 35.0,
              child: GeneratedStatusDurationWidget4(),
            ),
            Positioned(
              left: 195.0,
              top: 218.0,
              right: null,
              bottom: null,
              width: 147.0,
              height: 35.0,
              child: GeneratedStatusDurationWidget5(),
            ),
            Positioned(
              left: 42.0,
              top: 218.0,
              right: null,
              bottom: null,
              width: 142.0,
              height: 236.0,
              child: GeneratedCategorycardWidget4(),
            ),
            Positioned(
              left: 42.0,
              top: 133.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 51.0,
              child: GeneratedNavigationbarWidget7(),
            ),
            Positioned(
              left: 42.0,
              top: 39.0,
              right: null,
              bottom: null,
              width: 374.0,
              height: 71.0,
              child: GeneratedExerciseTitleWidget20(),
            )
          ]),
    ));
  }
}
