import 'package:flutter/material.dart';
import 'package:flutterapp/workoutapp/generatedthumbnailwidget/generated/GeneratedGroup107Widget1.dart';
import 'package:flutterapp/workoutapp/generatedthumbnailwidget/generated/GeneratedMockupsWidget1.dart';
import 'package:flutterapp/workoutapp/generatedthumbnailwidget/generated/GeneratedEllipse97Widget1.dart';

/* Frame Thumbnail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedThumbnailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 812.0,
        height: 632.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 247, 252),
                ),
              ),
              Positioned(
                left: -360.55194091796875,
                top: -129.91998291015625,
                right: null,
                bottom: null,
                width: 1469.8837890625,
                height: 858.9199829101562,
                child: GeneratedEllipse97Widget1(),
              ),
              Positioned(
                left: 31.900070190429688,
                top: 78.00001525878906,
                right: null,
                bottom: null,
                width: 408.976806640625,
                height: 432.88629150390625,
                child: GeneratedGroup107Widget1(),
              ),
              Positioned(
                left: 391.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 463.06280517578125,
                height: 438.0697937011719,
                child: GeneratedMockupsWidget1(),
              )
            ]),
      ),
    ));
  }
}
