import 'package:flutter/material.dart';
import 'package:flutterapp/workoutapp/generatedcoverwidget/generated/GeneratedFrame7Widget.dart';
import 'package:flutterapp/workoutapp/generatedcoverwidget/generated/GeneratedBgWidget.dart';

/* Frame Cover
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCoverWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 960.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 960.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 247, 247, 252),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1920.0,
                              height: 960.0,
                              child: GeneratedBgWidget(),
                            ),
                            Positioned(
                              left: 210.0,
                              top: 139.0,
                              right: null,
                              bottom: null,
                              width: 1500.0,
                              height: 680.753662109375,
                              child: GeneratedFrame7Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
