import 'package:flutter/material.dart';
import 'package:flutterapp/workoutapp/generatedactivitypagewidget/generated/GeneratedHourlyactivity2Widget.dart';
import 'package:flutterapp/workoutapp/generatedactivitypagewidget/generated/GeneratedThisweekWidget.dart';
import 'package:flutterapp/workoutapp/generatedactivitypagewidget/generated/GeneratedCardsWidget.dart';
import 'package:flutterapp/workoutapp/generatedactivitypagewidget/generated/GeneratedGraphWidget.dart';
import 'package:flutterapp/workoutapp/generatedactivitypagewidget/generated/GeneratedMenuWidget.dart';
import 'package:flutterapp/workoutapp/generatedactivitypagewidget/generated/GeneratedYouractivitiesWidget.dart';
import 'package:flutterapp/workoutapp/generatedactivitypagewidget/generated/GeneratedExerciseDetailsScrollingFrameWidget.dart';
import 'package:flutterapp/workoutapp/generatedactivitypagewidget/generated/GeneratedNavigationbarWidget.dart';
import 'package:flutterapp/workoutapp/generatedactivitypagewidget/generated/GeneratedHourlyactivityWidget.dart';
import 'package:flutterapp/workoutapp/generatedactivitypagewidget/generated/Generated1080kcalWidget.dart';

/* Frame Activity Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedActivityPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 27.0,
                child: GeneratedMenuWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 31.0,
                child: GeneratedYouractivitiesWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 26.0,
                child: GeneratedThisweekWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 74.0,
                child: GeneratedCardsWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 29.0,
                child: Generated1080kcalWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 368.0001220703125,
                right: null,
                bottom: null,
                width: 414.0,
                height: 202.9998779296875,
                child: GeneratedGraphWidget(),
              ),
              Positioned(
                left: 81.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 276.0,
                child: GeneratedHourlyactivityWidget(),
              ),
              Positioned(
                left: 308.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 276.0,
                child: GeneratedHourlyactivity2Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 249.0,
                child: GeneratedExerciseDetailsScrollingFrameWidget(),
              ),
              Positioned(
                left: -1.0,
                top: 845.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 51.0,
                child: GeneratedNavigationbarWidget(),
              )
            ]),
      ),
    ));
  }
}
