import 'package:flutter/material.dart';
import 'package:flutterapp/workoutapp/generatedactivitypage10amispressedwidget/generated/Generated1680kcalWidget1.dart';
import 'package:flutterapp/workoutapp/generatedactivitypage10amispressedwidget/generated/GeneratedHourlyactivityWidget2.dart';
import 'package:flutterapp/workoutapp/generatedactivitypage10amispressedwidget/generated/GeneratedNavigationbarWidget2.dart';
import 'package:flutterapp/workoutapp/generatedactivitypage10amispressedwidget/generated/GeneratedMenuWidget4.dart';
import 'package:flutterapp/workoutapp/generatedactivitypage10amispressedwidget/generated/GeneratedExerciseDetailsScrollingFrameWidget2.dart';
import 'package:flutterapp/workoutapp/generatedactivitypage10amispressedwidget/generated/GeneratedYouractivitiesWidget2.dart';
import 'package:flutterapp/workoutapp/generatedactivitypage10amispressedwidget/generated/GeneratedCardsWidget2.dart';
import 'package:flutterapp/workoutapp/generatedactivitypage10amispressedwidget/generated/GeneratedThisweekWidget2.dart';
import 'package:flutterapp/workoutapp/generatedactivitypage10amispressedwidget/generated/GeneratedHourlyactivity2Widget2.dart';
import 'package:flutterapp/workoutapp/generatedactivitypage10amispressedwidget/generated/GeneratedGraphWidget4.dart';

/* Frame Activity Page (10AM is pressed)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedActivityPage10AMispressedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 27.0,
                child: GeneratedMenuWidget4(),
              ),
              Positioned(
                left: 15.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 31.0,
                child: GeneratedYouractivitiesWidget2(),
              ),
              Positioned(
                left: 17.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 26.0,
                child: GeneratedThisweekWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 74.0,
                child: GeneratedCardsWidget2(),
              ),
              Positioned(
                left: 19.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 29.0,
                child: Generated1680kcalWidget1(),
              ),
              Positioned(
                left: 1.0,
                top: 360.8697509765625,
                right: null,
                bottom: null,
                width: 414.0,
                height: 210.1302490234375,
                child: GeneratedGraphWidget4(),
              ),
              Positioned(
                left: 81.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 242.0,
                child: GeneratedHourlyactivityWidget2(),
              ),
              Positioned(
                left: 308.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 242.0,
                child: GeneratedHourlyactivity2Widget2(),
              ),
              Positioned(
                left: 21.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 249.0,
                child: GeneratedExerciseDetailsScrollingFrameWidget2(),
              ),
              Positioned(
                left: -1.0,
                top: 845.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 51.0,
                child: GeneratedNavigationbarWidget2(),
              )
            ]),
      ),
    ));
  }
}
